monocle/db/db.py
=> Add branch and target_branch in db schema

monocle/github/pullrequest.py
Issue: https://github.com/morucci/monocle/issues/4
=> github: store the branch names

monocle/gerrit/review.py
=> Add branch and target_branch in gerrit crawler

README.md, monocle/gerrit/review.py, monocle/github/pullrequest.py, monocle/main.py, web/src/components/changes.js, web/src/components/common.js
- link to github PR/gerrit changes and author
=> improve UI

monocle/projects.py, requirements.txt
Use jsonschema to define the projects.yaml file format.
Provide a schema example and validation.
Related to #15
=> Initialise base schema for a projects.yaml config file

docker-compose.yml, monocle/crawler.py, monocle/db/db.py, monocle/main.py
- add dependencies between services in docker-compose.yml
- test the connection before using the elastic API
=> cleaner start of crawler

README.md, monocle/crawler.py, monocle/gerrit/review.py, monocle/github/pullrequest.py, monocle/main.py, monocle/projects.py, monocle/webapp.py, web/src/App.js, web/src/api.js, web/src/components/approvals.js, web/src/components/changes.js, web/src/components/changes_lifecycle.js, web/src/components/changes_review.js, web/src/components/common.js, web/src/components/filtersform.js, web/src/components/menu.js, web/src/components/top.js, web/src/reducers/filters.js
- allow to specify the name of the index in the projects.yaml file
- all the URL are prefixed by the index name
Issue: https://github.com/morucci/monocle/issues/17
=> expose the index name

monocle/db/queries.py, monocle/main.py, monocle/projects.py, monocle/utils.py, monocle/webapp.py, web/package-lock.json, web/package.json, web/src/App.js, web/src/api.js, web/src/components/approvals.js, web/src/components/changes.js, web/src/components/changes_lifecycle.js, web/src/components/changes_review.js, web/src/components/common.js, web/src/components/filtersform.js, web/src/components/top.js, web/src/reducers/query.js
- refactored all tables for Changes in ChangesTable
- make the id of a change a filter to the repository
- add 2 sub-pages: merged-changes and opened-changes
- pagination in the tables of the sub-pages
=> enhance navigation

web/.eslintrc.yml, web/package-lock.json, web/package.json, web/src/App.js, web/src/App.test.js, web/src/api.js, web/src/components/approvals.js, web/src/components/changes.js, web/src/components/changes_lifecycle.js, web/src/components/changes_review.js, web/src/components/common.js, web/src/components/filtersform.js, web/src/components/menu.js, web/src/components/top.js, web/src/index.js, web/src/reducers/filters.js, web/src/reducers/query.js, web/src/serviceWorker.js, web/src/store.js
- configure eslint
- fix all reports
=> web: eslint support

contrib/pre-commit
- check js files with eslint
- check only staged files to be faster
- git add python files to avoid having to rerun git commit
if black modifies something
=> improve git pre-commit hook (eslint + speed)

monocle/db/db.py, monocle/gerrit/review.py, monocle/github/pullrequest.py
=> Add changed_files details in crawlers

web/src/components/changes.js, web/src/components/complexity_graph.js, web/src/reducers/query.js
Complexity = (files+additions+deletions)
=> web: ChangesTable add column with Complexity about changes

monocle/db/db.py, monocle/db/queries.py, monocle/gerrit/review.py, monocle/github/pullrequest.py, monocle/main.py, monocle/utils.py, web/src/App.js, web/src/api.js, web/src/components/change.js, web/src/components/changes.js, web/src/components/common.js, web/src/components/complexity_graph.js, web/src/reducers/query.js
- db: repository_fullname_and_number -> change_id
- db: do not use / and # in change_id to be url friendly
- web: implement /:index/change/:change_id
Issue: https://github.com/morucci/monocle/issues/73
=> Implement a page with the information about a change

CHANGELOG.md, monocle/gerrit/review.py, tests/unit/test_crawler_gerrit.py, tests/unit/test_crawler_github.py
* Add missing changelog entry
* Also remove the print as dumper in the test context
=> Changelog mf

monocle/db/db.py, monocle/gerrit/review.py, monocle/github/pullrequest.py, tests/unit/fixtures/datasets/github.com-morucci-monocle-70_extracted.json, tests/unit/fixtures/datasets/github.com-morucci-monocle-70_raw.json, tests/unit/fixtures/datasets/github.com-wazo-platform-wazo-ansible-76_extracted.json, tests/unit/fixtures/datasets/github.com-wazo-platform-wazo-ansible-76_raw.json, tests/unit/fixtures/datasets/https:__gerrit-review.googlesource.com-gerrit-246332_extracted.json, tests/unit/fixtures/datasets/https:__gerrit-review.googlesource.com-gerrit-246332_raw.json
=> Commits listing

CHANGELOG.md, web/src/components/changes.js, web/src/components/filtersform.js, web/src/components/menu.js, web/src/components/my_link.js, web/src/components/top.js
- filtersform: hack the current URL before pushing the new one to allow to go back.
- fork Link into MyLink to support the same hack for navigation
=> web: allow to go back if the search filter changes

web/src/components/changes.js, web/src/components/filtersform.js
=> Fix JS console errors

monocle/db/queries.py, monocle/main.py, monocle/utils.py, tests/unit/test_queries.py, web/package-lock.json, web/package.json, web/src/App.js, web/src/api.js, web/src/components/approvals.js, web/src/components/authors_merged_pie.js, web/src/components/authors_opened_pie.js, web/src/components/change.js, web/src/components/changes.js, web/src/components/changes_lifecycle.js, web/src/components/changes_review.js, web/src/components/common.js, web/src/components/files_treemap.js, web/src/components/repos_merged_pie.js, web/src/components/repos_opened_pie.js, web/src/components/top.js, web/src/reducers/query.js
- new requests: changes_by_file_map and authors_by_file_map
- files param (regexp to filter on changed_files.path)
=> web: visualize changes on files using treemaps

CHANGELOG.md, monocle/db/db.py, monocle/webapp.py, tests/unit/common.py, tests/unit/test_queries.py, tox.ini, web/src/App.js, web/src/api.js, web/src/reducers/indices.js, web/src/store.js, web/src/top_view.js
- web: redirect to the first index if there is one or display a message
- api: add a /indices route returning the list of names of the index
- db: use the monocle.changes. prefix for index name
=> preliminary work on a home page

Dockerfile, docker-compose.yml, monocle/webapp.py, requirements.txt, web/src/App.js, web/src/api.js, web/src/components/menu.js, web/src/components/user.js, web/src/reducers/user.js, web/src/store.js
Create a Oauth APP in github developer setting and set
in docker-compose the CLIENT_ID and CLIENT_SECRET of Oauth APP.
Then go to localhost:3000/login, click on the link.
Once login, the logged user's github login should appear on the
right of the top menu.
=> Base support for github authentication

.gitignore, CHANGELOG.md, CONTRIBUTING.md, Dockerfile, README.md, docker-compose.yml.dev, docker-compose.yml.img, web/.dockerignore, web/Dockerfile, web/package-lock.json, web/package.json
- split README.md in README.md and CONTRIBUTING.md
- 2 options to consume: use container images from docker hub  or from source code
- add container config into `.env` to make sure nobody needs to edit `docker-compose.yml` files.
- make the README more compelling by explaining the benefits and philosophy and add 2 screenshots.
=> Improve UX

CHANGELOG.md, monocle/tests/unit/test_api.py, monocle/webapp.py, web/src/components/user.js
Also fix wrong http code when accessible not authorized index.
=> web: do not display login link if authentication is not configured

CHANGELOG.md, web/src/App.js, web/src/components/common.js, web/src/components/footer.js, web/src/components/menu.js
- fix the menu header.
- add a footer with a link to the monocle GitHub repo
- add a spinner in the LoadingBox.
=> [web] fixed menu header and footer + spinner in LoadingBox

CHANGELOG.md, web/src/App.js, web/src/components/authors_histo.js, web/src/components/changes_lifecycle.js, web/src/components/changes_review.js, web/src/components/common.js, web/src/components/filtersform.js, web/src/components/menu.js, web/src/components/pie.js
- add warning message for screen width < 1024
- move the approval dispersion pie in changes summary
- increase pie size from 100 to 200 to mitigate big legend effect
=> web - add warning message for screen width < 1024

CHANGELOG.md, monocle/config.py, monocle/crawler.py, monocle/gerrit/review.py, monocle/main.py
For situation where a self-signed certificate is used for the Gerrit
server this options might be useful.
=> [crawlers] gerrit - add http request insecure option

CHANGELOG.md, web/src/components/filtersform.js
This commit does not bring any changes into the filtersbox expect
it makes use of bootstrap breakpoint system.
=> [web] better responsive layout for the filtersbox

CHANGELOG.md, docker-compose.yml.dev, docker-compose.yml.img, monocle/db/db.py, monocle/db/queries.py, requirements.txt
This commit ensures a fresh installation on 7.7 with unittest
success. Fix #22
=> [database] switch to ElasticSearch from 6.8 to 7.7 engine

.github/workflows/publish-release.yaml
=> [WIP] CI: Add workflow for push tag

CHANGELOG.md, monocle/db/db.py, monocle/webapp.py, web/src/components/common.js
This changes also includes a mitigation attempt for the authors_histo that reach the max_buckets limit on some projects like k8s on with large time slice.
=> Better error display and handling when query fail

monocle/github/pullrequest.py
A simple change to improve readability of log files.
=> Add a space to log message to improve readability

monocle/github/pullrequest.py, monocle/tests/unit/fixtures/datasets/github_05efzdga.json, monocle/tests/unit/fixtures/datasets/github_10ts6fjd.json, monocle/tests/unit/fixtures/datasets/github_mflla1yj.json, monocle/tests/unit/test_crawler_github.py
- A comment object might be null
- A closed PR might have a closedAt value at null
- The totalCount of commits of a PR might be absent
=> Fix multiple corner case issues loading github PR from API

CHANGELOG.md, README.md, monocle/crawler.py, monocle/gerrit/review.py, monocle/main.py, monocle/tests/unit/fixtures/datasets/gerrit-review.googlesource.com-gerrit-246332_extracted.json, monocle/tests/unit/fixtures/datasets/gerrit-review.googlesource.com-gerrit-246332_raw.json, tox.ini
- allow to prefix projects by passing a prefix setting in the config file
- fix dumping of projects with / (bug #291)
- fix dumping data with cli (bug #293)
=> gerrit: allow to prefix projects and small fixes

CONTRIBUTING.md
This change documents how to run the python tests.
=> Add instructions to run the python tests

.github/workflows/publish-master.yaml, .github/workflows/publish-tag.yaml, .github/workflows/validate-pr.yaml
Avoid https://github.com/TristanCacqueray/monocle/actions
=> Avoid GHA to run on forked repositories

README.md
The current example is **raising** an error in monocle crawler
service.
=> Fix example config

.env
The .env file can be provided with default values.
=> Added .env file

.github/workflows/validate-pr.yaml, README.md
Those directories are required for Monocle installation.
=> Add data, etc and dump dir

.github/workflows/publish-master.yaml, .github/workflows/publish-tag.yaml, .github/workflows/validate-pr.yaml, README.md
This commit fixes other github workflows on creating directories
=> Change github workflow for creating  data, etc and dump dir

CHANGELOG.md, monocle/db/db.py, monocle/main.py, monocle/tests/unit/test_api.py, monocle/tests/unit/test_queries.py, monocle/webapp.py, tox.ini
Some Elasticsearch deployment may have user authentication and
also supporting encrypted communication.
=> Added user authentication and SSL support for Elasticsearch

CONTRIBUTING.md
This commit provide manual, how to start Monocle service for developing
purpose.
=> Added section for starting Monocle service without compose tool

CONTRIBUTING.md, contrib/start-with-podman.sh
=> New proposal for PR 325

Makefile, nix/README.md, nix/default.nix, shell.nix
This change adds a nix expression to setup the codegen tools.
=> [nix] Add derivations to setup codegen tools

doc/query-language.md, haskell/src/Monocle/Search/Lexer.hs, haskell/test/Spec.hs
This PR adds support for unicode value in search expression.
=> Unicode search

protos/monocle/change.json, web/README.md, web/bsconfig.json, web/build.js, web/src/Designer.res, web/src/components/Board.res, web/src/components/Change.res
=> [web] Add designer

doc/openapi.yaml, docker-compose.dhall, docker-compose.yml.dev, docker-compose.yml.img, haskell/codegen/Monocle/Config.hs, haskell/src/Monocle/Api/Client/Api.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Servant/HTTP.hs, monocle/config_pb2.py, monocle/config_pb2.pyi, protos/monocle/config.proto, protos/monocle/http.proto, web/src/components/WebApi.res, web/src/messages/ConfigBs.ml, web/src/messages/ConfigBs.mli, web/src/messages/ConfigTypes.ml, web/src/messages/ConfigTypes.mli
This change adds a missing endpoint and update the compose health check.
Fixes #416
=> [api] Add missing healthcheck endpoint

.github/workflows/haskell.yaml, .github/workflows/validate-pr.yaml, .gitignore, .gitmodules, Dockerfile-builder, doc/query-language.md, haskell/monocle.cabal, haskell/src/Monocle/Api/Config.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Prelude.hs, haskell/src/Monocle/Search/CLI.hs, haskell/src/Monocle/Search/Parser.hs, haskell/src/Monocle/Search/Query.hs, haskell/src/Monocle/Search/Syntax.hs, haskell/src/Monocle/Servant/Env.hs, haskell/test/Spec.hs, haskell/test/data/config.yaml, monocle/webapp.py, web/src/components/Board.res, web/src/components/Change.res, web/src/components/Search.res
This change enables decoding the whole configuration.
Fixes #407
=> [api] Add config type through Dhall.TH

doc/openapi.yaml, haskell/codegen/Monocle/Crawler.hs, haskell/src/Monocle/Api/Config.hs, haskell/src/Monocle/Api/Server.hs, protos/monocle/crawler.proto
=> [apiv2] Implement crawlerAddDoc, crawlerCommit, crawlerCommitInfo functions

haskell/src/Monocle/Api/Client/CrawlerWorker.hs, haskell/src/Monocle/Api/Config.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Documents.hs, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Test.hs
…we can get the oldest commited entity
=> [apiv2] Crawler - update backend to adjust with the MacroScope

.github/workflows/haskell.yaml, haskell/.stan.toml, haskell/monocle.cabal, haskell/src/Database/Bloodhound/Raw.hs, haskell/src/Monocle/Api/CLI.hs, haskell/src/Monocle/Api/Client/Internal.hs, haskell/src/Monocle/Api/Client/Worker.hs, haskell/src/Monocle/Api/Config.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Documents.hs, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Prelude.hs, haskell/src/Monocle/Search/CLI.hs, haskell/src/Monocle/Search/Parser.hs, haskell/src/Monocle/Search/Query.hs, haskell/src/Monocle/Search/Syntax.hs, haskell/src/Monocle/Servant/Env.hs, haskell/test/Spec.hs
=> Chore cleanup

haskell/monocle.cabal, haskell/src/Monocle/Api/CLI.hs, haskell/src/Monocle/Api/Config.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Search/CLI.hs, haskell/src/Monocle/Search/Parser.hs, haskell/src/Monocle/Search/Query.hs, haskell/test/Spec.hs, haskell/test/data/Config.dhall
=> Search field improvements

doc/openapi.yaml, doc/query-language.md, haskell/codegen/Monocle/Search.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Search/CLI.hs, haskell/src/Monocle/Search/Lexer.hs, haskell/src/Monocle/Search/Parser.hs, haskell/src/Monocle/Search/Query.hs, haskell/src/Monocle/Search/Syntax.hs, haskell/test/Spec.hs, monocle/search_pb2.py, monocle/search_pb2.pyi, protos/monocle/search.proto, web/src/components/Board.res, web/src/components/Search.res, web/src/components/SearchToolTip.res, web/src/components/Store.res, web/src/messages/SearchBs.ml, web/src/messages/SearchBs.mli, web/src/messages/SearchTypes.ml, web/src/messages/SearchTypes.mli
=> Search order improvement

.github/workflows/validate-pr.yaml, CHANGELOG.md, README.md, conf/config.yaml.sample, haskell/src/Macroscope/Main.hs, haskell/src/Monocle/Api/Config.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Test.hs, haskell/test/Spec.hs, haskell/test/data/Config.dhall, haskell/test/data/config.yaml, monocle/config.py, monocle/env.py, monocle/main.py, monocle/tests/unit/test_schemas.py
Fixes https://github.com/change-metrics/monocle/issues/466
=> Future proof the configuration

haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Backend/Test.hs, haskell/test/Integration.hs
=> apiv2 - add first backend implementation of topAuthors queries

README.md
=> [readme] Add link to changemetrics.io

haskell/src/Monocle/Backend/Queries.hs
- set getRepos to 5000 by defaults.
- others most active authors functions keeping it to default and will handle size through the API request (so tackling this in another PR)
=> apiv2 - termAgg can be parametrized for a size

CHANGELOG.md, haskell/src/Monocle/Api/Config.hs, haskell/src/Monocle/Backend/Test.hs, haskell/test/Spec.hs, monocle/config.py, monocle/env.py, monocle/tests/unit/test_api.py, monocle/tests/unit/test_schemas.py, monocle/webapp.py
Fixes https://github.com/change-metrics/monocle/issues/478
=> [api] Remove index acl

.github/workflows/publish-master.yaml, .github/workflows/publish-tag.yaml, .github/workflows/validate-pr.yaml, README.md, monocle/config.py, monocle/main.py, monocle/tests/unit/test_schemas.py
Follow-up for https://github.com/change-metrics/monocle/issues/495
=> [doc] Remove index references leftover

doc/openapi.yaml, haskell/codegen/Monocle/Search.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Backend/Test.hs, monocle/search_pb2.py, monocle/search_pb2.pyi, protos/monocle/search.proto, web/src/App.jsx, web/src/components/ActivePeopleView.res, web/src/components/Board.res, web/src/components/Prelude.res, web/src/components/menu.jsx, web/src/components/top.jsx, web/src/messages/SearchBs.ml, web/src/messages/SearchBs.mli, web/src/messages/SearchTypes.ml, web/src/messages/SearchTypes.mli
=> apiv2 - API support for top authors metrics

doc/openapi.yaml, haskell/codegen/Monocle/UserGroup.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Search/Query.hs, haskell/src/Monocle/Search/Syntax.hs, protos/monocle/user_group.proto, web/src/components/Canvas.res, web/src/components/GroupView.res, web/src/messages/UserGroupBs.ml, web/src/messages/UserGroupTypes.ml, web/src/messages/UserGroupTypes.mli
=> Group view improvement

Makefile, codegen/rename_bs_module.py, doc/openapi.yaml, haskell/codegen/Monocle/Search.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Prelude.hs, haskell/src/Monocle/Search/Query.hs, protos/monocle/search.proto, web/src/App.jsx, web/src/components/Activity.res, web/src/components/DateFromInt64.res, web/src/components/MLink.res, web/src/components/changes_lifecycle.jsx, web/src/components/changes_review.jsx, web/src/components/menu.jsx, web/src/messages/SearchBs.ml, web/src/messages/SearchBs.mli, web/src/messages/SearchTypes.ml, web/src/messages/SearchTypes.mli
=> Activity histo view

web/.prettierrc, web/src/components/Activity.res, web/src/components/change.jsx, web/src/components/complexity_graph.jsx, web/src/components/duration_complexity_graph.jsx
=> [web] Add change merged graph to the activity page

.github/workflows/publish-master.yaml, .github/workflows/publish-tag.yaml, .github/workflows/validate-pr.yaml, .gitignore, CHANGELOG.md, CONTRIBUTING.md, README.md, contrib/start-crawlers-legacy.sh, docker-compose.dhall, docker-compose.yml.dev, docker-compose.yml.img, haskell/monocle.cabal, haskell/src/Macroscope/Main.hs, haskell/src/Monocle/Api/Config.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Prelude.hs, haskell/test/Spec.hs, haskell/test/data/config.yaml, monocle/config.py, monocle/main.py, monocle/tests/unit/test_schemas.py, nix/default.nix
=> Replace inlined secrets with environment variable

deployment/api-deployment.yaml, deployment/api-legacy-deployment.yaml, deployment/api-legacy-service.yaml, deployment/api-service.yaml, deployment/crawler-deployment.yaml, deployment/crawler-legacy-deployment.yaml, deployment/elastic-data-persistentvolumeclaim.yaml, deployment/elastic-deployment.yaml, deployment/elastic-service.yaml, deployment/monocle-config.yaml, deployment/web-deployment.yaml, deployment/web-service.yaml
- remove .metadata.creationTimestamp
=> fix(deployment): minor fixes

web/src/components/Change.res
Related to https://github.com/change-metrics/monocle/issues/548
=> Web change improvements

web/src/App.res, web/src/components/ActivePeopleView.res, web/src/components/Activity.res
=> Patternfly improvements

haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Search/Query.hs, web/src/components/Search.res, web/src/components/Store.res
=> Web order improvements

haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Env.hs, haskell/src/Monocle/Search/Query.hs, haskell/test/Spec.hs
=> Fix the new contributor query

haskell/src/Database/Bloodhound/Raw.hs, haskell/src/Monocle/Backend/Index.hs
https://github.com/change-metrics/monocle/issues/572
=> Configure index with max_regex_length

haskell/monocle.cabal, haskell/src/Monocle/Api.hs, haskell/src/Monocle/Env.hs
This change integrates the fast-logger library to handle flushing the log buffer.
=> Add fast logger

CHANGELOG.md, haskell/src/Monocle/Backend/Queries.hs, web/src/components/NChangeView.res, web/src/components/ReposView.res
This change changes the name to better reflect the column values.
=> [web] Update the repo view column title

.github/workflows/validate-pr.yaml, Dockerfile-web, web/bsconfig.json, web/package-lock.json, web/package.json, web/src/components/Query.res, web/src/components/Query.test.res
This change adds a Expr parser for rescript so that the query
can be manipulated client side too.
=> [web] Add search query parser

haskell/src/Monocle/Search/Query.hs, haskell/src/Monocle/Test/Spec.hs
This change improves the search query to be easier to read.
=> [query] Combine similar boolean expression into a single list

contrib/client.py, doc/openapi.yaml, haskell/codegen/Monocle/TaskData.hs, haskell/src/Lentille/Bugzilla.hs, haskell/src/Lentille/GitHub/Issues.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Documents.hs, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Provisioner.hs, haskell/src/Monocle/Backend/Test.hs, monocle/task_data_pb2.py, monocle/task_data_pb2.pyi, protos/monocle/task_data.proto, web/src/components/Change.res, web/src/messages/TaskDataBs.ml, web/src/messages/TaskDataTypes.ml, web/src/messages/TaskDataTypes.mli
This PR enables displaying task data using a custom prefix.
=> Add task data prefix

haskell/monocle.cabal, haskell/src/Database/Bloodhound/Raw.hs, haskell/src/Macroscope/Worker.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Documents.hs, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Janitor.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Env.hs, haskell/src/Monocle/Prelude.hs, haskell/src/Monocle/Test/Spec.hs
This change implements a more efficient scanSearch using the streaming library.
=> [api] Add Streaming query scan search

docker-compose.dhall, docker-compose.yml.dev, docker-compose.yml.img
=> Add macroscope healthcheck test in docker-compose

haskell/src/Macroscope/Main.hs, haskell/src/Macroscope/Test.hs, haskell/src/Macroscope/Worker.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Class.hs, haskell/src/Monocle/Prelude.hs
This PR is a follow-up for #682
=> [backend] Improve parallel crawlers logging

deployment/crawler-deployment.yaml, deployment/elastic-deployment.yaml, deployment/web-deployment.yaml
now all resources have working liveness (aside legacy-crawler that I
assume will be deleted soon enough)
=> fix(deploy): add liveness to all

.github/workflows/static_analysis.yml
you can test this locally with 'act -j check-k8s' with https://github.com/nektos/act
=> feat(deployment): validate k8s #725

.mergify.yml
This is a follow-up for #731 to fix mergify.
=> [ci] Update mergify rules for the new build name

nix/default.nix
This PR adds `cabal test` to the nix ci task to start the migration from the haskell action.
=> [ci] Run the unit test in the nix task

nix/default.nix
This change prevents caching useless artifact from a CI run.
=> [ci] Do not copy the sources in the $out result

CHANGELOG.md, web/src/App.res, web/src/components/HelpSearch.res, web/src/components/Store.res
The username is used by the query language to resolve the 'self' value
of the author field.
=> [web] Add a login/logout mechanics to handle the username setting

.mergify.yml
See https://blog.mergify.com/strict-mode-deprecation/
=> [ci] Mergify - update config due to deprecation

haskell/src/Monocle/Api/Server.hs
This change uses the MonadPlus instance of MaybeT to interupt the
traversal when the user if found in a workspace.
=> [backend] Improve user validation by stopping at the first valide

.github/workflows/k8s.yaml
now we don't need to worry about touching the action versions anymore (until it breaks something on our end
=> feat(k8s): use stable versions

haskell/src/CLI.hs, haskell/src/Lentille.hs, haskell/src/Lentille/GitHub/Issues.hs, haskell/src/Lentille/GitHub/Organization.hs, haskell/src/Lentille/GitHub/PullRequests.hs, haskell/src/Lentille/GitHub/RateLimit.hs, haskell/src/Lentille/GitLab/Group.hs, haskell/src/Lentille/GitLab/MergeRequests.hs, haskell/src/Lentille/GraphQL.hs, haskell/src/Macroscope/Main.hs, haskell/src/Macroscope/Worker.hs, haskell/src/Monocle/Logging.hs
This PR adds some work arounds for the recent issues introduced by the new crawler implementation.
=> Improve crawler errors handling

haskell/src/Lentille.hs, haskell/src/Lentille/Bugzilla.hs, haskell/src/Lentille/Gerrit.hs, haskell/src/Lentille/GitHub/RateLimit.hs, haskell/src/Lentille/GraphQL.hs, haskell/src/Macroscope/Worker.hs, haskell/src/Monocle/Api.hs, haskell/src/Monocle/Class.hs, nix/default.nix
This PR unifies the retry facilities to simplify the code.
=> Refactor the MonadRetry

haskell/monocle.cabal, haskell/src/Lentille/GitHub/User.hs
Usage will be to be able to enhance Identities into Monocle with extra
info fetched from a GitHub provider.
=> [crawler] Add Module Lentille.GitHub.User

haskell/monocle.cabal, haskell/src/CLI.hs, haskell/src/Monocle/Client.hs, haskell/src/Monocle/Prelude.hs, haskell/src/Monocle/Test/Spec.hs, haskell/test/Spec.hs
=> [crawler] Use openssl for graphql client

haskell/monocle.cabal, haskell/src/Lentille/Bugzilla.hs, haskell/src/Lentille/Bugzilla/Spec.hs, haskell/src/Lentille/BugzillaMock.hs, haskell/src/Macroscope/Main.hs, nix/default.nix
This change adds support for the latest bugzilla-redhat version.
Fixes #838
=> [crawler] Support bugzilla-redhat version 1.0

haskell/src/Monocle/Backend/Queries.hs
=> [backend] Add first events metric documentation

web/src/components/AuthorSearch.res
After an un-successful query we need to display "No results".
=> [wabapp] make the search authors page to display "No results"

CHANGELOG.md, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Test.hs
=> [backend] improve how Doc ID is generated for Task Data

CONTRIBUTING.md, doc/openapi.yaml, haskell/codegen/Monocle/Protob/Metric.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Client/Api.hs, haskell/src/Monocle/Prelude.hs, haskell/src/Monocle/Servant/HTTP.hs, haskell/src/Tests.hs, nix/default.nix, protos/monocle/protob/http.proto, protos/monocle/protob/metric.proto, web/src/components/WebApi.res, web/src/messages/MetricBs.ml, web/src/messages/MetricBs.mli, web/src/messages/MetricTypes.ml, web/src/messages/MetricTypes.mli
=> Metric get endpoint

CONTRIBUTING.md, haskell/src/CLI.hs, haskell/src/Database/Bloodhound/Raw.hs, haskell/src/Json/Extras.hs, haskell/src/Lentille.hs, haskell/src/Lentille/Bugzilla.hs, haskell/src/Lentille/Bugzilla/Mock.hs, haskell/src/Lentille/Gerrit.hs, haskell/src/Lentille/GitHub/Issues.hs, haskell/src/Lentille/GitLab/Adapter.hs, haskell/src/Lentille/GitLab/Group.hs, haskell/src/Lentille/GitLab/MergeRequests.hs, haskell/src/Lentille/GraphQL.hs, haskell/src/Macroscope/Main.hs, haskell/src/Macroscope/Test.hs, haskell/src/Macroscope/Worker.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Documents.hs, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Janitor.hs, haskell/src/Monocle/Backend/Provisioner.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Config.hs, haskell/src/Monocle/Env.hs, haskell/src/Monocle/Logging.hs, haskell/src/Monocle/Prelude.hs, haskell/src/Monocle/Search/Query.hs, haskell/src/Tests.hs, haskell/test/JsonDecode.hs
This change will help if/when the relude dependency is removed.
=> Replace relude convertions helper with Witch.from

.github/workflows/ci.dhall, .github/workflows/publish-builder.yaml, .github/workflows/publish-master.yaml, .github/workflows/publish-tag.yaml
monocle repository was not created on quay.io. So let's revert
that change.
This reverts commit 4fd0979705959aee2f832bdd11b783eba46bf5e0.
=> Revert "[ci] fix publish jobs"

haskell/src/Monocle/Backend/Queries.hs
- metricReviewsCount
- metricReviewAuthorsCount
- metricCommentsCount
- metricCommentAuthorsCount
=> Add other simple metrics to Metric system

doc/openapi.yaml, haskell/codegen/Monocle/Protob/Metric.hs, haskell/codegen/Monocle/Protob/Search.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Backend/Test.hs, protos/monocle/protob/metric.proto, protos/monocle/protob/search.proto, web/src/components/Activity.res, web/src/components/HistoBox.res, web/src/messages/MetricBs.ml, web/src/messages/MetricBs.mli, web/src/messages/MetricTypes.ml, web/src/messages/MetricTypes.mli, web/src/messages/SearchBs.ml, web/src/messages/SearchTypes.ml, web/src/messages/SearchTypes.mli
related #847 
This change finalize the migration of metrics in the new metric system.
=> Add more metrics exposed as trend in the new metric system

nix/default.nix, src/Lentille/GitHub/RateLimit.hs, src/Macroscope/Main.hs, src/Monocle/Search/Parser.hs, src/Monocle/Search/Query.hs
This change uses the same ormolu versions as the one from HLS to
ensure consistant formating.
=> Pin ormolu to version 0.4

.gitignore, codegen/Monocle/Protob/Metric.hs, doc/openapi.yaml, schemas/monocle/protob/metric.proto, src/Monocle/Api/Server.hs, src/Monocle/Backend/Queries.hs, src/Monocle/Search/Query.hs, web/src/messages/MetricBs.ml, web/src/messages/MetricTypes.ml, web/src/messages/MetricTypes.mli
Related to  https://github.com/change-metrics/monocle/issues/847
=> Handle Metric trend query interval

monocle.cabal, src/CLI.hs
See https://github.com/cnr/cgroup-rts-threads#why
=> Integrate cgroup-rts-threads to better handle RTSopts

codegen/Monocle/Protob/Metric.hs, codegen/Monocle/Protob/Search.hs, doc/openapi.yaml, schemas/monocle/protob/metric.proto, schemas/monocle/protob/search.proto, src/Monocle/Api/Server.hs, src/Monocle/Backend/Queries.hs, src/Monocle/Backend/Test.hs, src/Monocle/Servant/HTTP.hs, web/src/components/ActivePeopleView.res, web/src/components/NChangeView.res, web/src/components/NewContributorsView.res, web/src/messages/MetricBs.ml, web/src/messages/MetricBs.mli, web/src/messages/MetricTypes.ml, web/src/messages/MetricTypes.mli, web/src/messages/SearchBs.ml, web/src/messages/SearchBs.mli, web/src/messages/SearchTypes.ml, web/src/messages/SearchTypes.mli
The effort is part of https://github.com/change-metrics/monocle/issues/847
Move some Top metrics under the new metric system.
=> Move some Top style metrics into new metric system

.github/workflows/k8s.yaml, Makefile, deployment/README.md, deployment/api-deployment.yaml, deployment/crawler-deployment.yaml, deployment/monocle-config.yaml
This change is related to #936 
- It fixes and improves k8s manifests in deployment/
- Adds extended usage doc in deployment/README.md
=> Update k8s maniftests and README.md

monocle.cabal, nix/default.nix, src/Lentille.hs, src/Lentille/Bugzilla.hs, src/Lentille/Gerrit.hs, src/Lentille/GitHub/Issues.hs, src/Lentille/GitHub/Organization.hs, src/Lentille/GitHub/PullRequests.hs, src/Lentille/GitHub/RateLimit.hs, src/Lentille/GitHub/User.hs, src/Lentille/GitHub/Watching.hs, src/Lentille/GraphQL.hs, src/Macroscope/Main.hs, src/Macroscope/Test.hs, src/Macroscope/Worker.hs, src/Monocle/Api/Server.hs, src/Monocle/Api/Test.hs, src/Monocle/Backend/Index.hs, src/Monocle/Backend/Provisioner.hs, src/Monocle/Backend/Test.hs, src/Monocle/Class.hs, src/Monocle/Effects.hs, src/Monocle/Main.hs, src/Monocle/Prelude.hs
This change also simplifies the LentilleStream implementation to remove the Error side channel
=> Integrate retry-effectfull

web/src/components/Activity.res, web/src/components/Change.res, web/src/components/chartjs.jsx
=> Fix complexity term typo

web/src/components/Change.res
=> Add tooltip for complexity badge

CHANGELOG.md, web/src/components/Search.res
=> [api] - fix order by task's score

web/src/Designer.res, web/src/components/Board.res, web/src/components/Change.res, web/src/components/MonoIndexedDB.res, web/src/components/NChangeView.res, web/src/components/PinnedChanges.res
This change adds a new Pin feature.
Now the user can highlight the issue to follow issues changes better.
Related issue: https://github.com/change-metrics/monocle/issues/819
=> Pin Feature Added

CHANGELOG.md, README.md
=> Add doc about metric API usage

nix/default.nix
=> nix: disable elasticsearch geoip

CHANGELOG.md, README.md, src/CLI.hs, src/Monocle/Backend/Janitor.hs
=> [cli] Add janitor wipe-crawler-data command

README.md
=> README - Provide more information about the github token

CHANGELOG.md, src/Monocle/Main.hs
=> api - disable /health and /metrics request logging

README.md
This has been discussed on
https://github.com/change-metrics/monocle/discussions/1040
=> README.md - Add users listing table

.github/workflows/docker.yaml, .github/workflows/mkCI.dhall, .github/workflows/publish-master.yaml, .github/workflows/publish-tag.yaml
This change tries to fix the docker ci.
=> ci: remove the patched docker container

README.md
This mini-PR updates the documented callback URL to match the calls actually being performed.
=> Update README for OIDC callback URI

src/Monocle/Api/Server.hs
=> Add debug around oidc user claim

README.md
=> doc - add a note about the global crawler config section

README.md, docker-compose.yml, k8s/api-deployment.yaml, monocle.cabal
This was missing the 1.11.2 release commit.
=> Fix wrong version number

src/CLI.hs
This change slightly improves the lentille commands with the --human parameter.
=> Display the change url in the lentille CLI

README.md
Also updating the troubleshooting section related to the `data` directory rights. This change was need from my side to run the compose via Podman compose.
=> doc - add a note about podman-compose usage

src/Lentille/GitLab/Adapter.hs, src/Lentille/GitLab/MergeRequests.hs, src/Monocle/Prelude.hs
A quick attempt to debug #1145
=> lentille - log invalid gitlab date

CHANGELOG.md, src/Monocle/Config.hs
Instead of file modification date. See #1150.
=> Config reload mechanism is now based on a checksum computation

src/CLI.hs, src/Lentille/GraphQL.hs, src/Macroscope/Main.hs, src/Macroscope/Test.hs, src/Monocle/Effects.hs
=> Use System.Timeout to ensure stalled network request terminates

DockerfileUBI
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>
=> DockerfileUBI for arm64
