README.md, monocle/gerrit/review.py, monocle/github/pullrequest.py, monocle/main.py
This commit also keeps useful debug launchers for crawlers.
It means keep a working main in crawlers for quick and easy
debug.
=> Finish cleaning of gerrit|github_crawler from cli

README.md, monocle/crawler.py, monocle/github/pullrequest.py, monocle/main.py, monocle/projects.py
This patch adds a new repository parameter in the crawler
definition for a Github. It then possible to select the repositories
we want to fetch data from instead of the full organization.
=> github crawler: repository support

monocle/db/queries.py, web/src/components/changes_lifecycle.js, web/src/components/changes_review.js
- exposed in the changes_lifecycle_stats API query
- exposed in the web "Changes lifecycle stats" graph + iteration/change
=> expose ChangeCommitForcePushedEvent and ChangeCommitPushedEvent

monocle/db/queries.py, web/src/components/top.js
This PR adds:
- events_tops pagination support
- add ChangeMergedEvents support in Changes lifecycle stats
- Move from median to average from green top (and increase fiability)
=> Improve tops authors

.dockerignore, README.md, docker-compose.yml, monocle/crawler.py, monocle/gerrit/review.py, monocle/github/graphql.py, monocle/github/pullrequest.py, monocle/main.py, requirements.txt, tests/unit/test_crawler_gerrit.py, tests/unit/test_crawler_github.py
- manage errors from github
- run a thread per Github token
- dump raw pr into the /var/lib/crawler if it exists
- manage empty authors as ghost
- retry multiple times if a graphql request fails
=> crawler: solidify github process

monocle/github/pullrequest.py, web/src/components/change.js
- do not dump all UNKNOWN PR as this doesn't help and use a lot of storage
- fix external URL in change details  fix #128
=> various fixes

CHANGELOG.md, web/src/components/change.js, web/src/components/common.js
=> web: have a correct history of events in /change/ when filtered on authors

monocle/github/pullrequest.py
=> github crawler: skip archived repositories

CHANGELOG.md, README.md, monocle/db/queries.py, monocle/main.py, monocle/tests/unit/fixtures/datasets/objects/unit_repo1.json, monocle/tests/unit/test_queries.py, monocle/utils.py, web/src/components/change.js, web/src/reducers/query.js
Detection is done during the query. This will add flexibility for later
as the Detector could be improved to be configurable by projects.
The Detector could also serve to build EL queries to filter on changes
having tests (according to project config)
Fix #150
=> query/ui: Move included tests detection of a change in the backend

CHANGELOG.md, monocle/db/db.py, monocle/db/queries.py, monocle/main.py, monocle/tests/unit/fixtures/datasets/objects/unit_repo1.json, monocle/tests/unit/test_detector.py, monocle/tests/unit/test_queries.py, monocle/utils.py, web/package-lock.json, web/package.json, web/src/components/change.js
At indexation ensure text ant title field are also indexed as keyword
to enable regexp search.
In the web API after the EL query for a change enhances the change
with:
- has_issue_tracker_links field: choice 'generic|github.com|altassian.net'
- issue_tracker_links: The list of matchers + replacements
At query time add the has_issue_tracker_links params to scope
on changes having the tracker links.
Add unit tests.
For now only support generic tracker url, github.com and altassian.net
=> Improve support for issue tracker links detection

CHANGELOG.md, web/src/App.js, web/src/components/connection_diagram.js
- put the new contributors at the end of the /people/ page
because the list can be long.
- make the peer strength graph smaller on the /people/ page.
=> [web] improve the /people/ page

CHANGELOG.md, monocle/github/graphql.py, monocle/github/pullrequest.py
- obey to the Retry-After header
- set the User-Agent header to change-metrics/monocle
- sleep 1 sec between calls
=> [crawler] improve compliance with GitHub rate limiting rules

CHANGELOG.md, monocle/db/queries.py, web/src/components/changes_lifecycle.js
When a change is closed and re-opened then the compute of changes
opened + merged + abandoned != changes created.
It was due to the compute method that was based on the events but not
on the status of the change.
Example of change: https://github.com/bitcoin/bitcoin/pull/18863
=> api, ui: Fix wrong abandoned ratio + count

CHANGELOG.md, monocle/db/queries.py, monocle/tests/unit/test_queries.py, web/src/App.js, web/src/components/authors_histo.js, web/src/reducers/query.js
This query with nested term aggregation will allow to build
histograms for events and changes based on authors.
Will be able to display the count of unique users by date
slots.
The query also compute the total uniq authors seens.
=> Add authors_histo histgram query

CHANGELOG.md, web/src/components/common.js
The change fixes a situation where the default gte is used (now-3months)
even if an older gte is specified. So a change appaering in changes listing
could not be clicked as the backend will return empty data.
=> [web] fix wrong backend query on the change page (gte missing)

CHANGELOG.md, monocle/db/queries.py, monocle/tests/unit/test_queries.py
This change fixes the query when called with a authors param set. The result
was 0 for opened/abandoned/merged changes (ratio too).
The use of switch_to_on_authors was incorrect since we changed the computation
method of opened/abandoned/merged changes count (no longer use event objects,
but change objects directly).
This change also removes un-used (by the Monocle UI) data from query computation.
=> [api] fix change_lifecycle_stats return null values when authors is set

CHANGELOG.md, monocle/config.py, monocle/github/application.py, monocle/github/pullrequest.py, monocle/main.py, web/src/components/pie.js
react-charjs2 does not handle well the pie legend that can be
too large and makes the engine decrease the pie size. Sometime
the graph is invisible.
This change lets the full size to the pie and compute + display
the legend ouside the chart.
=> [web]: pie charts: extracts legend outside the graph itself

monocle/github/pullrequest.py
Dacite makes it mandatory to provide the data and that's better.
This commit fixes a bug where a commit author or committer if
not provided by the Github API (probably a deleted or unknown user)
makes the dacite from_dict function to fail.
#271
=> [crawler] github: fix missing author or committer for commit #271

README.md
I suspect this is a remnant from a rename or migrating the repository to a organisation. It's still technically correct (in that it works), but perhaps best to change it for full clarity.
Feel free to disregard and close the PR if you disagree or think it's too small a change. :)
=> Update git url from morruci to change-metrics

.github/workflows/publish-tag.yaml
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> GHA: switch for olegtarasov/get-tag@v2.1

CHANGELOG.md, README.md, monocle/tests/unit/test_api.py, monocle/webapp.py
Some application like cauth is setting the REMOTE_USER
header, so additional authorization is not required.
=> Added support for REMOTE_USER header

CHANGELOG.md, README.md, monocle/config.py, monocle/tests/unit/test_api.py, monocle/utils.py, monocle/webapp.py
This commit provides project_definition support. It means
that you are able to define project in your index definition,
and monocle will return only informations related to
repositories-regex [1]. For example:
tenants:
- index: openstack
crawler:
loop_delay: 600
gerrit_repositories:
- name: "^openstack/.*"
updated_since: "2021-01-01"
base_url: https://review.opendev.org/
projects:
- name: infra
repositories-regex: "opendev/system-config|openstack/disskimage-builder"
The infra project definition returns statistics related only for those
repositories that are in repositories-regex.
[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html
=> Added project_definition support

monocle/webapp.py
After authorize the api redirected the logged user to localhost:9876.
=> [api] Fix wrong redirect after GitHub login

docker-compose.dhall, docker-compose.yml.dev, docker-compose.yml.img
W/o this default setting a local deployment will get an empty string
in place of the API base url.
=> Add default http://localhost:8080 to PUBLIC_URL when unset

doc/adr/0011-search-query-language.md, doc/query-language.md, haskell/app/Search.hs, haskell/cabal.project, haskell/monocle.cabal, haskell/src/Monocle/Search/CLI.hs, haskell/src/Monocle/Search/Change.hs, haskell/src/Monocle/Search/Lexer.hs, haskell/src/Monocle/Search/Parser.hs, haskell/src/Monocle/Search/Queries.hs, haskell/src/Monocle/Search/Query.hs, haskell/src/Monocle/Search/Syntax.hs, haskell/test/Spec.hs
Related:
- #344 : query language may be used to defined board kanban column content
- #265 : operator may be implemented to define full text search
- #167 : `state: open and updated_at < now-2week`
- #166 : `state: open and review_count: 0`
- #112 : `state: open and approval_count: 0`
- #111 : `state: open and approval_count > 0`
=> [doc] Add query language proposal

haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Search/CLI.hs, haskell/src/Monocle/Search/Query.hs, haskell/test/Spec.hs
This pull request improve the search syntax by adding support for:
- state field, e.g. `state:open`
- short and relative date, e.g. `updated_at > now-3weeks`
=> [search] Add state and relative date

Makefile, nix/default.nix
Error was:
sh -c 'for pb in monocle/config.proto monocle/search.proto monocle/task_data.proto; do compile-proto-file --includeDir /usr/include --includeDir protos/ --proto ${pb} --out haskell/src/; done'
Error: while processing include statements in "monocle/search.proto", failed
to find the imported file "google/protobuf/timestamp.proto", after looking in the following
locations (controlled via the --includeDir switch(es)):
/usr/include/google/protobuf/timestamp.proto
protos/google/protobuf/timestamp.proto
=> codegen-haskell: Fix missing include to protobuf-src

doc/openapi.yaml, haskell/codegen/Monocle/Crawler.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Test.hs, protos/monocle/crawler.proto
This change enables the macroscope to skip broken entities by
adding an offset to the request.
=> [api] Add offset to the getLastUpdated message

CONTRIBUTING.md, haskell/README.md, nix/default.nix
This change fixes this issue:
cabal: Cannot open a repl for multiple components at once
This change also includes a emacs-lisp script to launch all
the service at once.
=> Fix cabal repl usage and adds emacs launcher

haskell/src/Monocle/Backend/Queries.hs
This change counts the open changes and deduces the abandoned count to
ensure accurate result. This change also fixes the query flavor for
event document type which do not have updated_at field.
=> [query] Improve repo summary count calculation

haskell/monocle.cabal, haskell/src/Database/Bloodhound/Raw.hs, haskell/src/Json/Extras.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/test/JsonDecode.hs, haskell/test/JsonDecode.py
This change mitigates a performance issue happening with the firstEventDuration where the generic aeson decoder induce a noticable overhead.
Fixes #560
=> Improve firstEventDuration computation by using json-syntax

haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Env.hs, haskell/src/Monocle/Search/Query.hs, haskell/test/Spec.hs
This change enables a new flavor to set both on_created_at and created_at
range bounds. That is useful to compute elapsed time where we need both
bounds to be set to ensure changes and events are in the same time range.
=> Add OnCreatedAndCreated query flavor

conf/grafana-dashboard.dhall, haskell/monocle.cabal, haskell/src/Monocle/Api.hs, nix/default.nix
This change adds a new middleware to serve ghc metrics on the
/metrics endpoint.
=> Add prometheus client to monitor the API

CHANGELOG.md, haskell/src/Monocle/Backend/Queries.hs
This change optimizes two queries:
- compute the peer strength based on the provided limit (instead of the first 5000 authors).
- drop the project field for the per repository summary.
=> [api] Optimize repos and peer strength query

CHANGELOG.md, doc/query-language.md, haskell/src/Monocle/Search/Lexer.hs, haskell/test/Spec.hs, web/src/components/HelpSearch.res
This change simplifies the query language:
- Remove boolean operator symbols (&& or ¬)
- Remove whitespace around non boolean operators
=> [api] Simplify the query language

haskell/src/Monocle/Backend/Documents.hs, haskell/src/Monocle/Backend/Index.hs
Previously we were using `%FT%T` instead of the common `%FT%TZ`.
This change adds support for both formats.
=> [api] Support legacy task data updated_at value format

haskell/app/Api.hs, haskell/app/LentilleStandalone.hs, haskell/app/Macroscope.hs, haskell/monocle.cabal, haskell/src/CLI.hs
This change finishes the migration to a god library where
the common code is now part of the CLI module.
The goal being that ghcid automatically validate the new module.
=> [backend] Move all the CLI code to a single module

web/conf/start.sh
based on
https://github.com/change-metrics/monocle/pull/700#issuecomment-962612490
and https://github.com/change-metrics/monocle/pull/700#discussion_r739677465
the code needs to change in order to run in hardened environments
this is the solution for it.
the `sed -i.bak` has been tested swell but it seems that even in this
state there is an intermediary step that causes this failure
=> fix(web): make sed work on hardened-systems

docker-compose.dhall, docker-compose.yml.dev, docker-compose.yml.img
Previous command failed and resulted in unheathly state.
"Output": "/bin/sh: line 1: python: command not found\n"
=> [compose] fix api health check test command

README.md, conf/grafana-dashboard.dhall, haskell/src/CLI.hs, haskell/src/Lentille.hs, haskell/src/Lentille/Bugzilla.hs, haskell/src/Lentille/Gerrit.hs, haskell/src/Lentille/GraphQL.hs, haskell/src/Macroscope/Main.hs, haskell/src/Macroscope/Worker.hs, haskell/src/Monocle/Api.hs, haskell/src/Monocle/Api/Config.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Class.hs, haskell/src/Monocle/Env.hs, haskell/src/Monocle/Prelude.hs, nix/README.md, nix/default.nix
This PR enables basic http request count metrics.
This PR also improves the nix packages of prometheus and grafana to provide ready to use container image to monitor the backend performance.
=> [backend] Add crawler metrics

haskell/src/Monocle/Api/Config.hs, haskell/src/Monocle/Api/Server.hs
This fixes an issue where macroscope cannot process as the Map is
empty and resulting in error "Unknown workspace".
=> [api] fixes csWorkspaceStatus being empty at startup

haskell/src/Macroscope/Main.hs, haskell/src/Monocle/Prelude.hs
This change prevents loosing track of the monitoring service so that
it the macroscope can be safely reloaded from the REPL.
=> [backend] Wait for the crawler monitoring server to enable REPL reload

CHANGELOG.md, Dockerfile-api, deployment/api-deployment.yaml, deployment/crawler-deployment.yaml, docker-compose.dhall, docker-compose.yml.dev, docker-compose.yml.img, haskell/app/Api.hs, haskell/app/Macroscope.hs, haskell/app/Monocle.hs, haskell/monocle.cabal, haskell/src/CLI.hs
This change simplifies the command API by providing an "hyper" tool
with sub commands:
- monocle-api -> monocle api
- macroscope -> monocle crawler
- lentille -> monocle lentille
Then the janitor can be implemented as another sub command.
=> [backend] Use an unified CLI

monocle/db/db.py, monocle/main.py
- Ensure the config is loaded with auto translation to legacy schema.
- Do not fail if object does not have the 'type' field.
=> [update-idents] quick fix in legacy code

haskell/src/Lentille/GitHub/Issues.hs
Since morpheus 0.18 it seems the that __typename is mandatory
to ensure the decoding of the response to avoid runtime errors
such as:
```
[2021-12-01 11:16:49.341] Macroscope: [sf-team-workspace] Crawler: change-metrics-crawler - Error occured when consuming the document stream: HttpError ("FetchErrorParseFailure \"Error in $.data.search.nodes[1].timelineItems.nodes[0].source: key \\\"__typename\\\" not found on object\""
```
=> [crawler] github issues - ask __typename for all Union fields

haskell/src/Monocle/Search/Query.hs, web/src/components/Board.res, web/src/components/Search.res, web/src/components/Store.res
This PR let a user provide a username through the url:
- `&username=alice` : use this name and save it in the local storage
- `&username=` : remove the name from the local storage
- ``: use the name from the local storage, if any
This could use a better interface through some sort of a login modal, and to provide an indicator about the login state.
=> Add support for username configuration to use `self` in queries

.mergify.yml
k8s workflow only trigger when a change on deployment
is made and that does not fit well with the mergify
config preventing us to merge changes.
Let's disable this setting for the moment.
=> Remove check-k8s workflow from mergify

haskell/src/Macroscope/Main.hs, haskell/src/Macroscope/Test.hs
This change updates the getClientGraphQL to include the token
value inside the stream group name.
Indeed mulitple tokens could be used with a single url and to
prepare for handling the query quota (handled by Token) we need to
separate group by url/token as streams inside a group are
processed sequentialy.
=> [macroscope] ensures stream group key include the Token

.github/workflows/k8s.yaml
the upstream repo that was used incorporated required changes to change
the version of minikube used.
this allows running using a newer version then previously expected
=> fix(actions): use upstream action

docker-compose.dhall, docker-compose.yml.dev, docker-compose.yml.img
Port binding expect a fixed 9898/TCP internal port so the healthcheck
needs to follow the same rule.
=> [compose] healthcheck for api - do not honor MONOCLE_API_PORT

haskell/monocle.cabal, haskell/src/Lentille.hs, haskell/src/Macroscope/Main.hs, haskell/src/Macroscope/Test.hs, haskell/src/Monocle/Api.hs, haskell/src/Monocle/Api/Server.hs, haskell/src/Monocle/Api/Test.hs, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Class.hs, haskell/src/Monocle/Env.hs, haskell/src/Monocle/Logging.hs, haskell/src/Monocle/Prelude.hs, haskell/src/Monocle/Test/Spec.hs
This change adds fast-logger to the crawler, and merge both log event data types.
Fixes #803
=> Consolidate backend logging

CONTRIBUTING.md, README.md, haskell/README.md, nix/default.nix
- Renamed monocle-api2-start to monocle-repl
- Cleaning haskell/README.md as it was a duplicate of CONTRIBUTING.md
- Some slight re-org and intro improvement
- Reflecting nix changes into the CONTRIBUTING.md file
- Replace instruction regarding start-web.sh that has been removed from
contrib/
=> [DOC] Some improvements on nix commands/README.md/CONTRIBUTING.md

haskell/src/Lentille.hs, haskell/src/Lentille/GitHub/RateLimit.hs, haskell/src/Lentille/GitLab/Group.hs, haskell/src/Lentille/GitLab/MergeRequests.hs, haskell/src/Lentille/GraphQL.hs, haskell/src/Macroscope/Worker.hs
This change improves the graphql error so that the body and the response are displayed in the error log.
=> Improve exception handling

CHANGELOG.md, haskell/src/Monocle/Client.hs
This change enables setting https://www.openssl.org/docs/man1.1.1/man1/ciphers.html
Fixes #822
=> [crawler] Enable settings TLS_CIPHERS openssl option

CHANGELOG.md, haskell/src/Monocle/Backend/Queries.hs
Those queries list the most commented or reviewed change authors, but
when an author filter is specified we expect to get filtered on the
comment or review events created by the filtered author.
In other words, by filtering on an author we want to see on which change
authors a reviewer or commenter have been the most active.
=> [api] fix missusage of author filter for TOP_COMMENTED/TOP_REVIEWED queries

CHANGELOG.md, README.md, haskell/monocle.cabal, haskell/src/Lentille/Gerrit.hs, haskell/src/Monocle/Client.hs, nix/default.nix
This change removes the unsupported gerrit_url_insecure configuration
and adds support for the global TLS_NO_VERIFY flag for gerrit crawler.
Fixes: #840
=> [crawler] Honor the TLS_NO_VERIFY flag for gerrit

README.md
This change also fixes:
- Some wrong section identations for section regarding the config file
- Add missing shortcut to inner config sections
=> [readme] Add search aliases documentation

nix/default.nix
The fix was merged and the reference needs to be updated.
=> nix: update the proto3-suite reference

haskell/cabal.project
A new revision on hackage has been published that should
enable us to remove the constraint.
=> Remove turtle pinning as proto3-wire got a new revision

CHANGELOG.md, haskell/src/Monocle/Backend/Documents.hs, haskell/src/Monocle/Backend/Index.hs, haskell/src/Monocle/Backend/Provisioner.hs, haskell/src/Monocle/Backend/Queries.hs, haskell/src/Monocle/Backend/Test.hs, haskell/src/Monocle/Prelude.hs, haskell/src/Tests.hs
Part of the implementation of #847
This change includes 4 more simple metrics into the new Metrics system.
Furthermore during the migration of the self merged metric I've figured out that the metrics must rely on the Change Merged Event and not on the Change object. Thus this changes brings a fix for this and a schema migration to add self-merged attribute to ChangeMergedEvent.
=> More metrics under Metrics system

.github/workflows/mkCI.dhall, .github/workflows/web.yaml
To unlock https://github.com/change-metrics/monocle/pull/917
=> GHA: Ensure same version of nodejs than on NIX

nix/default.nix
Probably this no longer work with the previous version bump
of Elasticsearch.
Also this change makes elasticsearch-start script to create the
EL_HOME in ~/ instead of /var/lib that requires sudo.
=> Fix elasticsearch modules cannot be a link

flake.lock, flake.nix, nix/default.nix, src/CLI.hs, src/Database/Bloodhound/Raw.hs, src/Lentille/GitLab/MergeRequests.hs, src/Lentille/GraphQL.hs, src/Macroscope/Main.hs, src/Monocle/Api/Jwt.hs, src/Monocle/Api/Server.hs, src/Monocle/Backend/Index.hs, src/Monocle/Backend/Queries.hs, src/Monocle/Class.hs, src/Monocle/Main.hs
This change replace the local package set with a re-usable set
defined in podenv/hspkgs.
This change also bumps ghc to 9.2.4
=> Integrate hspkgs overlay for haskell dependency

.github/workflows/mkCI.dhall, .github/workflows/nix.yaml
This change enables publishing the cache when a change is merged.
=> Run cachix action on push

src/Monocle/Backend/Queries.hs
In a previous metric refactor, the merged and abandoned count was
using the hardcoded EChangeCreatedEvent event type instead of the
desired `dt` type.
=> Fix merged and abandoned count to use the right field

CHANGELOG.md, Dockerfile
This change ensures the git version built in the CI is properly passed to
the template haskell.
=> Update CHANGELOG about the new image name and fix commit in docker build

CHANGELOG.md, src/Monocle/Search/Query.hs, src/Tests.hs
It allows to filter changes changing at least a file path that match the regex. Change's events match as well as they own the same field.
#resolves #950
#resolves #544
=> api - add the `file` query field

README.md, docker-compose.yml, k8s/api-deployment.yaml, k8s/crawler-deployment.yaml
Made the default to last the stable instead of the master image. This will help to avoid Monocle user to experience issues because they deployed the very last image.
=> Set latest stable as default version for compose and k8s

nix/default.nix
Since the recent change to use nix to build the monocle container image, monocle was unable to find the ca-bundle.crt file.
=> Fix monocle unable to find CA bundle

src/Lentille/GitHub/Issues.hs, src/Lentille/GitHub/Organization.hs, src/Lentille/GitHub/PullRequests.hs, src/Lentille/GitHub/RateLimit.hs, src/Lentille/GraphQL.hs
According to #958, the rate limit system can be deactivated in GHE.
This change updates the Github PR crawler to handle a ratelimit returned as null by the API. In this case Macroscope's GraphQL stream handler does not check for the internal RateLimit object because stored as Nothing then the waiting delay to honor a ratelimit is skipped.
Related to issue: #958
This commit does not handle the case for other Github crawlers. If this is accepted some follow-up patches will be needed to handle this is other Github crawlers.
=> crawler - Github PR - relax ratelimit in case deactivated in GHE

CHANGELOG.md, monocle.cabal, src/Monocle/Api/ServerHTMX.hs, src/Monocle/Env.hs, src/Monocle/Main.hs, src/Monocle/Servant/HTMX.hs, src/Monocle/Servant/HTTPMain.hs, web/package-lock.json, web/package.json, web/src/Index.res, web/src/components/AuthorSearch.res, web/src/components/Prelude.res
The feature is similar. Instead the active search is rendered and managed server side thanks to lucid (server side) and htmx (web ui).
=> Convert the author search page to use htmx

CHANGELOG.md, src/Monocle/Api/Server.hs, src/Monocle/Backend/Queries.hs, src/Monocle/Backend/Test.hs, web/src/components/ActivePeopleView.res
Add new standalone metrics and migrate queries QUERY_TOP_REVIEWED_AUTHORS and QUERY_TOP_COMMENTED_AUTHORS to use them.
This should also fix the issue raised here [1] where discarding an author via the query was not taken in account.
[1] https://github.com/change-metrics/monocle/issues/973#issuecomment-1287215671
=> Add metricChangeReviewedAuthors and metricChangeCommentedAuthors

CHANGELOG.md, README.md, src/Lentille/GraphQL.hs
This fix makes use of the "Bearer" pattern which is supported by both Github and Gitlab.
Related-to: #985
=> Fix unsupported Authorization header pattern for Gitlab

CHANGELOG.md, web/src/components/Change.res
A draft change is only displayed as draft when the change is open.
This fix #993
=> [web] Fix state display for draft changes

web/build.js
For some reason the htmx integration for the search page is broken by the minification option.
Simply disable it, however it add a cost in term of JS bundle size.
=> [web] esbuild avoid identifier minification as it break htmx integration

web/package.json
The npm version provided via Fedora 35 (used to build the web UI) changed recently that raised a deps issue in our JS dependency libs.
This commit uses an override to mitigate the issue.
=> [npm] override deps constraint react-event-timeline

README.md, src/Monocle/Config.hs, src/Monocle/Main.hs
A warning log is displayed when:
- The expected envrionment varible that contain the OIDC secret is missing or empty.
- At least of mandatory OIDC setting is empty.
=> [auth] Add some logs when the OIDCProvider is misconfigured

doc/tutorial/graphql-query.md, monocle.cabal, nix/default.nix, src/Lentille/GitHub/Issues.hs, src/Lentille/GitHub/Organization.hs, src/Lentille/GitHub/PullRequests.hs, src/Lentille/GitHub/RateLimit.hs, src/Lentille/GitHub/Types.hs, src/Lentille/GitHub/User.hs, src/Lentille/GitHub/Watching.hs, src/Lentille/GitLab/Adapter.hs, src/Lentille/GitLab/Group.hs, src/Lentille/GitLab/MergeRequests.hs, src/Lentille/GraphQL.hs
This changes adapts the graphql client to work with the new generated code. Beside the simple new naming convention, the two other differences are:
- Removed variant partial field selector:
Before:
```haskell
data TimelineEvents =
PullRequestReview { author :: Text, status :: Status }
| PullRequestComment { author :: Text, comment :: Text } 
```
After:
```haskell
data PullRequestReview = PullRequestReview { author :: Text, status :: Status }
data PullRequestComment = PullRequestComment { author :: Text, comment :: Text }
data TimelineEvents =
TimelineEventsVariantPullRequestReview PullRequestReview
| TimelineEventsVariantPullRequestComment PullRequestComment
```
- Global types for PullRequest status needs to be generated manually, in the `Lentille.GitHub.Types` module.
Overall, this …
=> Update to latest morpheus-graphql-client-0.27

CONTRIBUTING.md, cabal-override.project, monocle.cabal
This commits re-organize the contributing documentation by trying to make it easier to understand and follow.
Mainly it remove the cabal way to keep only the nix way. The cabal build is not longer tested in the CI and known to be broken.
=> Re-organize the CONTRIBUTING doc

CHANGELOG.md, monocle.cabal, src/CLI.hs, src/Lentille/Bugzilla.hs, src/Lentille/Gerrit.hs, src/Lentille/GraphQL.hs, src/Macroscope/Main.hs, src/Macroscope/Test.hs, src/Monocle/Config.hs, src/Monocle/Prelude.hs
This change uses the Hashable instance to group network client.
Fixes #1013
=> Rename unSecret into unsafeShowSecret to cleanup leak in the logs

flake.nix, nix/default.nix
Provide a monitoring shell: nix develop .#monitoriing
This saves disk space when entering a monocle dev shell. Those tools are extra for the specific monitoring use case.
=> Remove prometheus and grafana from default shell

flake.nix, nix/default.nix
This change enables integrating the monocle package into an external set.
=> nix: export the haskellExtend overlay

CHANGELOG.md, src/Monocle/Api/Server.hs, src/Monocle/Backend/Queries.hs, src/Monocle/Backend/Test.hs, src/Monocle/Effects.hs, src/Monocle/Search/Query.hs, src/Tests.hs, web/src/components/PeersStrengthView.res
Update peer strength metric computation to enable filtering by change author
Fixes: #1037
This change updates the computation where now we:
Find (and filter on) changes authors and for each of them find all event authors that did a comment/review on the change author.
The previous computation was that:
Find (and filter on) comments/reviews events authors and for each of them find all changes authors on which the event's author did a comment/review.
This change also:
- Updates the web UI for the peer strength to set the author colunm on the left.
- Keeps the previous computation code but unused for now. If the previous computation is relevant we could add a switch in the UI.
=> Update peer strength metric computation to enable filtering by change author

README.md
Was faced with the following error when trying to setup monocle on a remote host:
Ends-up I needed to set `MONOCLE_PUBLIC_URL` to my host name to make the queries succeed, but the error was a bit confusing, so I'm at least suggesting a troubleshooting entry for this.
=> add troubleshooting entry for network error message on web ui

src/Lentille/GitHub/RateLimit.hs, src/Lentille/GraphQL.hs, src/Macroscope/Test.hs, src/Macroscope/Worker.hs, src/Monocle/Backend/Test.hs
This change avoids retrying requests that fail with a 401 error. #1060
=> Handle Authentication Error

CHANGELOG.md, src/CLI.hs, src/Lentille.hs, src/Lentille/GitHub/PullRequests.hs, src/Lentille/GitHub/Types.hs, src/Lentille/GitHub/UserPullRequests.hs, src/Lentille/GitLab/MergeRequests.hs
This change ensure errors are kept in the stream.
=> Update the breakOnDate logic to take into account error

CHANGELOG.md, src/Monocle/Backend/Documents.hs, src/Monocle/Backend/Index.hs, src/Monocle/Backend/Provisioner.hs, src/Monocle/Backend/Test.hs
This change fixes an issue that happen when filtering by branch in the search query then resulting graphs are empty. This was because most of the graph related metrics computation relies on the ChangeEvent docs. Adding the missing field fixes that issue.
fix #1065
=> crawler: Fix target branch field not set on ChangeEvent Docs

CHANGELOG.md, codegen/Monocle/Protob/Change.hs, schemas/monocle/protob/change.proto, src/Lentille/Gerrit.hs, src/Lentille/GitHub/GraphQLFragments.hs, src/Lentille/GitHub/PullRequests.hs, src/Lentille/GitHub/UserPullRequests.hs, src/Lentille/GitHub/Utils.hs, src/Lentille/GitLab/MergeRequests.hs, src/Monocle/Backend/Documents.hs, src/Monocle/Backend/Index.hs, src/Monocle/Backend/Provisioner.hs, src/Monocle/Backend/Test.hs
=> crawler - github - index the mergeCommit's sha

nix/default.nix
Here is the command executed in the container context:
```
/bin/sh -c curl --silent --fail localhost:9001/health || exit 1
```
Since the move to UBI 8 image, sh is available under /usr/bin/sh. This change ensures a link from /bin/sh to /usr/bin/sh.
Attempt to fix #1078
=> docker - healthcheck assumes /bin/sh

CHANGELOG.md, src/Monocle/Client.hs
=> Add support for http proxy

CHANGELOG.md, src/Lentille/Gerrit.hs, src/Monocle/Client.hs, src/Monocle/Effects.hs
=> crawler: use a different proxy environment for the api

CHANGELOG.md, src/CLI.hs, src/Database/Bloodhound/Raw.hs, src/Effectful/Servant.hs, src/Macroscope/Test.hs, src/Monocle/Api/Server.hs, src/Monocle/Api/ServerHTMX.hs, src/Monocle/Api/Test.hs, src/Monocle/Backend/Index.hs, src/Monocle/Backend/Provisioner.hs, src/Monocle/Backend/Queries.hs, src/Monocle/Backend/Test.hs, src/Monocle/Effects.hs, src/Monocle/Main.hs
This change improves error reporting when the elastic client throws errors. The implementation is done in the `Monocle.Effects` module.
=> Catch elasticsearch error within the API

src/Monocle/Backend/Documents.hs, src/Monocle/Backend/Index.hs, src/Monocle/Backend/Janitor.hs, src/Monocle/Backend/Test.hs
When deploying the new schema, the existing documents does not have a groups attribute set, so this change reflect that to the data type.
=> index: change the groups to optional for migration purpose

CHANGELOG.md, src/Monocle/Backend/Documents.hs
This fixes an issue reported here:
https://github.com/change-metrics/monocle/issues/1084
monocle: esAdvance: Original error was: Error in $.hits.hits[2905]['_source']: parsing Monocle.Backend.Janitor.EChangeEventAuthors(EChangeEventAuthors) failed, key "id" not found Error parse failure was: Error in $: key "status" not found, req: "FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFkJtNFFLQW82UjhDR21YRVRpTnNuVXcAAAAAAAAA8xZmMDFyRzVFeVJjR2VVUFVZMGNxZ0t, resp: {"_scroll_id":"FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFkJtNFFLQW82UjhDR21YRVRpTnNuVXcAAAAAAAAA8xZmMDFyRzVFeVJjR, tb: [("throwError",SrcLoc {srcLocPackage = "monocle-1.11.0-2ShLfwfFjyo1H0paLD2SMi", srcLocModule = "Monocle.Effects", srcLocFile = "src/Monocle/Effects.hs", srcLocStartLine = 403, srcLocStartCol = 15, srcLocEndLine …
=> Fix missing EError doc in AllEventTypes

.github/workflows/docker.yaml, .github/workflows/mkCI.dhall, .github/workflows/publish-master.yaml, .github/workflows/publish-tag.yaml, CHANGELOG.md, README.md, src/Lentille.hs, src/Lentille/GitHub/Issues.hs, src/Lentille/GitHub/Organization.hs, src/Lentille/GitHub/PullRequests.hs, src/Lentille/GitHub/UserPullRequests.hs, src/Lentille/GitHub/Watching.hs, src/Lentille/GitLab/Group.hs, src/Lentille/GitLab/MergeRequests.hs, src/Lentille/GraphQL.hs, src/Macroscope/Worker.hs
When Monocle discovers organization's repositories it might happen that later repositories are deleted then the Changes crawler may encounter GraphQL queries issues. Such case in now handled and the stream silently continue on that case.
This effort could be subject to followup. But this first change might solve the issue #1112
=> Ensure Github PR fetching repo not found non fatal for stream

.github/workflows/mkCI.dhall, .github/workflows/nix.yaml, CHANGELOG.md, docker-compose.yml, k8s/elastic-deployment.yaml, nix/default.nix
This is the last Z release available for ElasticSearch.
=> elastic - bump from 7.17.16 to 7.17.26

flake.lock, flake.nix, monocle.cabal, nix/default.nix, src/CLI.hs, src/Json/Extras.hs, src/Macroscope/Test.hs, src/Monocle/Backend/Queries.hs, src/Monocle/Backend/Test.hs, src/Monocle/Logging.hs, src/Monocle/Main.hs
First tentative to move our Haskell stack to a higher and stable version of the stack. We rely on podenv/hspkgs to provide a nix derivation for a Haskell package set.
Here we attempt a bump to hspkgs for ghc 9.6.4.
=> Bump to ghc 9.6.6 from Nix latest

src/Monocle/Client.hs
The default value of `Network.HTTP.Client` is 30 seconds, however we've spotted that some provider might have trouble to deal with complexes graphQL queries within that delay.
This change propose to double the value (60 seconds).
=> Increase the default Monocle.Client HTTP request timeout

CHANGELOG.md, src/Lentille/GitLab/MergeRequests.hs
Be more respectful with regard to Gitlab provider as querying a large amount of data can raise 500 errors on Gitlab when responding to the graphQL query.
Ideally this value should be adaptative like for the Gitlab crawler, but let first decrease that value from 100 to 25.
=> crawler - gitlab - lower the bulk amount of MR to fetch

codegen/MonocleCodegen.hs, web/src/App.res, web/src/components/WebApi.res
Fixed redundant slash issue in App.res:
Changed WebApi.serverUrl ++ "/" ++ "api/2/auth/login?redirectUri=" to WebApi.serverUrl ++ "/api/2/auth/login?redirectUri="
Modified code generation in MonocleCodegen.hs:
Changed requestCall = camel name <> "Raw(serverUrl ++ \"" <> path <> "\")" to requestCall = camel name <> "Raw(\"" <> path <> "\")"
This ensures that the generated ReScript code uses direct API paths
Updated all API calls in WebApi.res to use direct paths:
Modified all modules (Login, Auth, Config, Search, Metric, Crawler)
Changed from methodRaw(serverUrl ++ "/api/2/path") to methodRaw("/api/2/path")
All 20 API endpoints now use direct paths
This approach has several benefits:
Prevents issues with double slashes or incorrect URL construction
Makes the code more maintainable and …
=> Fixes https://github.com/change-metrics/monocle/issues/1128
